name: Run Tests

on: [push, pull_request]  # Trigger on both push and PR events

jobs:
  test:
    runs-on: ubuntu-latest
    
    # Service for browser testing (optional but recommended)
    services:
      chrome:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - uses: actions/checkout@v4  # Updated to v4
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Updated to v4
      with:
        python-version: '3.9'  # Keep your preferred version
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-driver  # Required for headless Chrome
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html allure-pytest  # Added Allure for richer reports
    
    - name: Run tests
      run: |
        pytest --html=reports/pytest_html_report.html --self-contained-html \
               --alluredir=reports/allure-results
        
    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: reports/pytest_html_report.html
        
    - name: Generate Allure report
      if: always()
      run: |
        allure generate reports/allure-results -o reports/allure-report --clean
        
    - name: Upload Allure report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: reports/allure-report